### ISSUE TITLE
[feature request] SRT file translate

### ISSUE THREAD

**Issue by BramFr** [khakers/go-subgen#13]
I like your project :) thanks 
I have a feature request could you create a webhook for translate srt file from eng to (selected lang?)

Example:
webhooks/generic

```json
{
    "srt": ["/foo/bar/file.eng.srt", "/xxx/yyy/file.eng.srt"]
}
```

Every eng.srt will be translated to selected languages

**Comment by khakers** [comment]
It would be possible, but would require integrating with one (or more) translation services. I think it's a bit out of scope for this project, at least at the moment.
