### ISSUE TITLE
Are there any options for the microphone input?

### ISSUE THREAD

**Issue by guowei-gong** [khakers/go-subgen#34]
I'd like to get the input audio from the microphone and then whisper it into a regular text file

**Comment by khakers** [comment]
go-subgen itself doesn't have any way to process microphone input. It would be technically possible for it to process audio files and output non srt formatted text, but it's not built in currently, and wouldn't be very high on the priority list.

If you want near real time transcription, there's likely other software much better suited to that. I believe [whisper.cpp](https://github.com/ggerganov/whisper.cpp) has a (near) real time demo, and there is likely applications built using it that are designed for transcription that would be much easier to use.

**Comment by guowei-gong** [comment]
Okay, thanks for the reply.

I saw you mention `whisper.cpp` in the `READED.md` of the project, I tried that project and would like to build it in my own Go project, but ran into some [problems](https://github.com/ggerganov/whisper.cpp/discussions/312#discussioncomment-6731485), have you encountered any?

**Comment by khakers** [comment]
I would take a look at the docker compose files in this repo to see how I got it working. CGO can be a bit of a pain and there are a lot of ways to accidently screw it up.

**Comment by guowei-gong** [comment]
My English is not particularly good, would you like me to take a look at
the `docker.compose` file?
I seem to be using a CGO approach to bring it in, I'm not sure.
I introduced it according to its [documentation](
https://github.com/ggerganov/whisper.cpp/tree/master/bindings/go#using-the-bindings),
but the introduction failed.

khakers ***@***.***> 于2023年8月16日周三 09:40写道：

**Comment by guowei-gong** [comment]
> I would take a look at the dockerfiles in this repo to see how I got it working. CGO can be a bit of a pain and there are a lot of ways to accidently screw it up.

My English is not particularly good, would you like me to take a look at the `docker.compose` file?
I seem to be using a CGO approach to bring it in, I'm not sure.
I introduced it according to its [documentation](https://github.com/ggerganov/whisper.cpp/tree/master/bindings/go#using-the-bindings), but the introduction failed.

**Comment by khakers** [comment]
Sorry, I meant this [dockerfile](https://github.com/khakers/go-subgen/blob/master/Dockerfile). I misspoke originally. I can't say much about compiling on MacOS, but I'll do some testing on wsl later. That said, I don't see any errors in the actual c++ compilation you've shown in the other thread.

**Comment by guowei-gong** [comment]
> Sorry, I meant this [dockerfile](https://github.com/khakers/go-subgen/blob/master/Dockerfile). I misspoke originally. I can't say much about compiling on MacOS, but I'll do some testing on wsl later. That said, I don't see any errors in the actual c++ compilation you've shown in the other thread.

Yes, it struck me as very strange. My test case is passing.

Thank you.

**Comment by guowei-gong** [comment]
I'll try to use the way you did in the `dockerfile`, I think it's useful but haven't experimented with it yet.

Thanks for taking your valuable time!
